version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dozen/ruby-marshal
    docker:
      - image: cimg/go
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go test -v -race ./...
